services:

  app:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: teamdiff