services:

  #app:
  #  depends_on:
  #    - db
  #  build:
  #    dockerfile: Dockerfile
  #  ports:
  #    - 8080:8080
  #  env_file:
  #    - .env
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: teamdiff
  #meili:
    #  image: getmeili/meilisearch:v1.14
    #  restart: always
        #  ports:
    #    - 7700:7700
      #  environment:
    #    MEILI_KEY: miaou
        #  volumes:
  #    -
