services:

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/${APP_ENV}/Dockerfile
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    networks:
      - teamdiff

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/${APP_ENV}/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - teamdiff

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - teamdiff

  meili:
    image: getmeili/meilisearch:v1.14
    restart: always
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    volumes:
      - meili_data:/meili_data
    networks:
      - teamdiff

volumes:
  meili_data:
  pgdata:

networks:
  teamdiff:
