name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: 32cls
          password: ${{ secrets.PAT_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 32cls/${{ github.event.repository.name }}:latest
